blog/urls.py
from django.conf.urls import url
from .import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^about/$',views.about,name='about'),
    url(r'^contact/$',views.contact,name='contact'),
    url(r'^categories/$',views.categories_list,name='cats'),
    url(r'^post/(?P<id>[0-9]{1,3})$',views.post,name='post'),
    url(r'^category/(?P<id>[0-9]{1,3})$',views.categorypost,name='catposts'),


]

mehrab/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blog.urls',namespace='blog')),

]

if settings.DEBUG is True:
    		urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from django.contrib.auth.models import User
# Create your models here.

    
class Category(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=150)
    picture = models.ImageField(upload_to='category/%y/%m/%d/')

    def __unicode__(self):
        return self.name


class Post(models.Model):
    owner = models.ForeignKey(to=User)
    title = models.CharField(max_length=120)
    picture = models.ImageField(upload_to='posts/%y/%m/%d/')
    content = models.TextField()
    publish_datetime = models.DateTimeField(auto_now=False,auto_now_add=True)
    update_datetime = models.DateTimeField(auto_now=True,auto_now_add=False)
    category = models.ForeignKey(to=Category,default=2)

class Comment(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField()
    website = models.URLField()
    text  = models.TextField()
    for_post = models.ForeignKey(to=Post)
    publish_time = models.DateTimeField(auto_now=False,auto_now_add=True)

class ContactMe(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField()
    website = models.URLField(null=True,blank=True)
    message = models.TextField()

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, HttpResponseRedirect
from.models import Post,Comment,ContactMe,Category

from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
# Create your views here.
def sidebar():
    posts = Post.objects.all().order_by('-publish_datetime')
    recetn_posts = posts[:5]
    return recetn_posts


def index(request):
    posts = Post.objects.all().order_by('-publish_datetime')
    pginator = Paginator(posts,6)
    page = request.GET.get('page')
    try:
        posts = pginator.page(page)
    except PageNotAnInteger:
        posts = pginator.page(1)
    except EmptyPage:
        posts = pginator.page(pginator.num_pages)
    context = {
        'posts':posts,
        'recent_post':sidebar(),
    }
    return render(request,'index.html',context)

def about(request):
    return render(request,'about.html')

def contact(request):
    if request.method == 'POST':
        this_name = request.POST['name']
        this_email = request.POST['email']
        this_url = request.POST['url']
        this_message = request.POST['message']

        ContactMe.objects.create(name=this_name,email=this_email,website=this_url,message=this_message)
        return HttpResponseRedirect('/contact/')


    return render(request,'contact.html')

def post(request,id):
    this_post = Post.objects.get(id=id)
    if request.method == 'POST':
        this_name = request.POST['name']
        this_email = request.POST['email']
        this_url = request.POST['url']
        this_message = request.POST['message']
        Comment.objects.create(name=this_name,email=this_email,website=this_url,text=this_message,for_post=this_post)
        return HttpResponseRedirect(redirect_to='/post/{}'.format(id))
    comments = Comment.objects.filter(for_post=this_post)
    context = {
        'post':this_post,
        'comments':comments,
        'comments_numb':int(len(comments)),
        'recent_post':sidebar()
    }
    return render(request,'post.html',context)

def categories_list(request):
    categories = Category.objects.all()
    context = {
        'categories':categories,
    }
    return render(request,'categories.html',context)

def categorypost(request,id):
    this_category = Category.objects.get(id=id)
    posts = Post.objects.filter(category=this_category)
    context = {
        'posts':posts,
    }
    return render(request,'index.html',context)

blog/templates/about.html
{% extends "base.html" %}
{% block title %}
  {{ block.super }} | about-me
{% endblock title %}
{% block content %}}
<section class="main-content">
    <div class="padding">
        <div class="container">
            <div class="about-me">
                <div class="avatar text-center"><img src="/media/images/mehrab.jpeg" alt="Avatar" class="img-circle"></div><!-- /.avatar -->

                <div class="details">
                    <div class="details-top text-center">
                        <h2 class="section-title">About me</h2><!-- /.section-title -->
                    </div><!-- /.details-top -->
                    <p>
                        <b>start a story...</b>
                    </p>
                    <p>Hello to everyone my name is mehrab a programmer from IR</p>
                    <p>I love so many things in the world,I'm a geek and a programmer. if I wnat to name my first degree, I must say <b>Freedom</b></p>
                    <blockquote>
                        "web developing ,reading books and Of course guitar playing is the best funny things in my life : )"
                    </blockquote>
                    <p>
                            I have a dream.
                            I must continuously acquire knowledge.
                            I must Hard work and have perseverance.
                            Should not be afraid of problems.
                    </p>
                    <p>
                        I started web development when I have 14 years old and I learn more things every day : )
                    </p>
                    <p>
                        I hope for <b>freedom</b> 
                    </p>
                    <p>
                        <b>Thanks for reading this text</b>
                    </p>
                </div><!-- /.details -->
                
                <div class="social text-center">
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-pinterest-p"></i></a>
                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-google-plus"></i></a>
                    <a href="#"><i class="fa fa-instagram"></i></a>
                </div>
            </div><!-- /.about-me -->
        </div><!-- /.container -->
    </div><!-- /.padding -->
</section><!-- /.main-content -->


{% endblock content %}

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}
        Mehrab
    {% endblock title %}</title>
    <meta name="description" content="Mehrab babapour - blog">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="apple-touch-icon.png">

    <!-- Import Icon Packs -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/elegent-icons.css' %}">

    <!-- Import External Scrpit CSS Files -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">

    <!-- Import Template CSS Files -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <link rel="stylesheet" href="{% static 'css/themes.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

    <!-- <script src="//cdnjs.cloudflare.com/ajax/libs/less.js/2.7.2/less.min.js"></script> -->

    <script src="{% static 'js/modernizr-2.8.3.min.js' %}"></script>

</head>


<body>

    <div class="overlay-wrapper">

        <header class="masthead">
            <div class="header-top">
                <div class="container">
                    <div class="side-menu-trigger"><span class="trigger-icon"><i class="icon_menu"></i></span></div><!-- /.side-menu-trigger -->
                    <a class="navbar-brand hidden-xs" href="./"><h2>mehrab</h2></a>
                    <!--<a class="navbar-brand hidden-xs" href="./"><h2>mehrab</h2></a>-->
                    <div class="menu-search">
                        <div class="form-trigger"><i class="icon_search"></i></div>
                        <form action="#">
                            <input type="text" name="search" id="menu-search" placeholder="Search here..">
                        </form>
                    </div>

                    <nav class="sidebar-menu">
                        <a class="navbar-brand" href="./"><h3>mehrab</h3></a>
                        <span class="menu-close"><i class="icon_close"></i></span>

                        <ul class="nav navbar-nav">
                            <li class="menu-item {% if request.resolver_match.url_name == 'index' %} active {% endif %}">
                                <a href="/">Home</a>
                            </li>
                            <li class="menu-item {% if request.resolver_match.url_name == 'cats' %} active {% endif %}"><a href="{% url 'blog:cats' %}">Categories</a></li>
                            <li class="menu-item {% if request.resolver_match.url_name == 'about' %} active {% endif %}"><a href="{% url 'blog:about' %}">About</a></li>
                            <li class="menu-item {% if request.resolver_match.url_name == 'contact' %} active {% endif %}"><a href="{% url 'blog:contact' %}">Contact</a></li>
                        </ul><!-- /.navbar-nav -->

                        <div class="menu-social">
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-pinterest-p"></i></a>
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-youtube"></i></a>
                        </div><!-- /.menu-social -->
                    </nav><!-- /.sidebar-menu -->
                </div><!-- /.container -->
            </div><!-- /.header-top -->
            <div class="header-bottom">
                <div class="container">
                    <nav class="navbar navbar-default">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-menu" aria-expanded="false">
                                <i class="fa fa-bars"></i>
                            </button>
                            <!--<a class="navbar-brand visible-xs" href="./"><img src="/media/images/logo3.png" alt="Site Logo"></a>-->
                        </div>

                        <div id="main-menu" class="collapse navbar-collapse">
                            <ul class="nav navbar-nav">
                                <li class="menu-item {% if request.resolver_match.url_name == 'index' %} active {% endif %}">
                                    <a href="/">Home</a>
                                </li>
                                <li class="menu-item {% if request.resolver_match.url_name == 'cats' %} active {% endif %}"><a href="{% url 'blog:cats' %}">Categories</a></li>
                                <li class="menu-item {% if request.resolver_match.url_name == 'about' %} active {% endif %}"><a href="{% url 'blog:about' %}">About</a></li>
                                <li class="menu-item {% if request.resolver_match.url_name == 'contact' %} active {% endif %}"><a href="{% url 'blog:contact' %}">Contact</a></li>
                            </ul><!-- /.navbar-nav -->
                        </div><!-- /.navbar-collapse -->
                    </nav>
                </div><!-- /.container -->
            </div><!-- /.header-bottom -->
        </header><!-- /.masthead -->
        {% block content %}
          
        {% endblock content %}
        
        <footer class="site-footer colophon">
            <div class="container">
                <div class="row">
                    <div class="col-sm-3">
                        <a href="./" class="footer-logo pull-left"><h5 style="color:#fff">mehrab</h5></a><!-- /.footer-logo -->
                    </div>

                    <div class="col-sm-6">
                        <div class="copyright text-center">
                            © <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Design with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://github.com/mehrabcz/" target="_blank">mehrab</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </div><!-- /.copyright -->
                    </div>

                    <div class="col-sm-3">
                        <div class="footer-social pull-right">
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-pinterest-p"></i></a>
                        </div><!-- /.footer-social -->
                    </div>
                </div><!-- /.row -->
            </div><!-- /.container -->
        </footer><!-- /.site-footer -->

    </div><!-- /.overlay -->

    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

blog/templates/categories.html
{% extends "base.html" %}
{% block title %}
  {{ block.super }} | categories
{% endblock title %}
{% block content %}
  
<section class="main-content">
    <div class="padding">
        <div class="container">
            <div class="row">
                <div class="categories text-center">
                    <div class="details-top">
                    <h2 class="section-title">Categories</h2><!-- /.section-title -->
                    </div><!-- /.details-top -->
                    {% for category in categories %}
                    <div class="col-sm-4">
                        <article class="post type-post">
                            <div class="entry-thumbnail"><img src="/media/{{category.picture}}" alt="Thumbnail Image"></div><!-- /.entry-thumbnail -->
                            <div class="entry-content">
                            <span class="category"><a href="{% url 'blog:catposts' category.id %}">{{category.name}}</a></span><!-- /.category -->
                                <h2 class="entry-title"><a href="{% url 'blog:catposts' category.id %}">{{category.name}}</a></h2><!-- /.entry-title -->
                                <p>
                                    {{category.description}}
                                </p>

                                <a href="{% url 'blog:catposts' category.id %}" class="btn">Read more</a><!-- /.btn -->
                            </div><!-- /.entry-content -->
                        </article><!-- /.post -->
                    </div>
                    {% endfor %}
                </div><!-- /.categories -->
            </div><!-- /.row -->
        </div><!-- /.container -->
    </div><!-- /.padding -->
</section><!-- /.main-content -->

{% endblock content %}

blog/templates/contact.html
{% extends "base.html" %}
{% block title %}
  {{ block.super }} | contact-me
{% endblock title %}
{% block content %}
<section class="main-content">
    <div class="padding">
        <div class="container">
            <div class="contact">
                <div class="contact-top">
                    <div class="padding text-center">
                        <img src="/media/images/c.png" alt="Image">
                    </div><!-- /.padding -->
                </div><!-- /.contact-top -->

                <div class="contact-details">
                    <div class="details-top text-center">
                        <h2 class="section-title">Contact me</h2><!-- /.section-title -->
                    </div><!-- /.details-top -->
                    <p>
                         If you would like to contact with me, use the form below.
                    </p>
                    <p>
                        Maybe with a little delay, but i'll surely answer : )
                    </p>
                    
                    <form action="" method="post" class="wpcf7-form">
                        {% csrf_token %}
                        <span class="wpcf7-form-control-wrap your-name">
                            <input type="text" name="name" id="name" class="wpcf7-form-control" placeholder="Name" required>
                        </span>
                        <span class="wpcf7-form-control-wrap email">
                            <input type="email" name="email" id="email" class="wpcf7-form-control" placeholder="Email" required>
                        </span>
                        <span class="wpcf7-form-control-wrap url">
                            <input type="url" name="url" id="url" class="wpcf7-form-control" placeholder="Website*">
                        </span>
                        <span class="wpcf7-form-control-wrap message">
                            <textarea name="message" id="message" class="wpcf7-form-control" placeholder="Your Message" required></textarea>
                        </span>
                        <span class="wpcf7-form-control-wrap submit">
                            <input type="submit" name="submit" id="submit" class="wpcf7-form-control" value="Submit">
                        </span>
                    </form>
                </div><!-- /.contact-details -->
            </div><!-- /.contact -->
        </div><!-- /.container -->
    </div><!-- /.padding -->
</section><!-- /.main-content -->
{% endblock content %}

blog/templates/index.html
{% extends "base.html" %}
{% block title %}
  {{ block.super }} | blog
{% endblock title %}
{% block content %}
  <!--<section class="banner-slider banner-slider-02 owl-carousel owl-theme">
            <div class="item">
                <article class="post type-post">
                    <div class="entry-thumbnail">
                        <img src="/media/images/slider/02/s1.jpg" alt="Slider Image">
                    </div>
                    <div class="entry-content">
                        <div class="overlay">
                            <div class="inner-content">
                                <span class="category"><a href="categories.html">Lifestyle</a></span>
                                <h2 class="entry-title"><a href="standard.html">Natural summer</a></h2>
                                <a href="standard.html" class="btn read-more">Read More</a>
                            </div>
                        </div>
                    </div>
                </article>
            </div>

            <div class="item">
                <article class="post type-post">
                    <div class="entry-thumbnail">
                        <img src="/media/images/slider/02/s2.jpg" alt="Slider Image">
                    </div>
                    <div class="entry-content">
                        <div class="overlay">
                            <div class="inner-content">
                                <span class="category"><a href="categories.html">Lifestyle</a></span>
                                <h2 class="entry-title"><a href="standard.html">Cruise to Alaska</a></h2>
                                <a href="standard.html" class="btn read-more">Read More</a>
                            </div>
                        </div>
                    </div>
                </article>
            </div>

            <div class="item">
                <article class="post type-post">
                    <div class="entry-thumbnail">
                        <img src="/media/images/slider/02/s3.jpg" alt="Slider Image">
                    </div>
                    <div class="entry-content">
                        <div class="overlay">
                            <div class="inner-content">
                                <span class="category"><a href="categories.html">Lifestyle</a></span>
                                <h2 class="entry-title"><a href="standard.html">Natural summer</a></h2>
                                <a href="standard.html" class="btn read-more">Read More</a>
                            </div>
                        </div>
                    </div>
                </article>
            </div>
        </section>-->
        <section class="main-content">
            <div class="padding">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-8">
                            <div class="list-posts">
                                {% for post in posts %}
                                <article class="post type-post media">
                                    <div class="entry-thumbnail media-left pull-left"><img src="/media/{{post.picture}}" alt="Thumbnail Image"></div><!-- /.entry-thumbnail -->
                                    <div class="entry-content media-body">
                                        <span class="category"><a href="{% url 'blog:catposts' post.category_id %}">{{post.category.name}}</a></span><!-- /.category -->
                                        <h2 class="entry-title"><a href="{% url 'blog:post' post.id %}">{{post.title}}</a></h2><!-- /.entry-title -->
                                        <span class="time"><time datetime="2017-12-05">{{post.update_datetime}}</time></span><!-- /.time -->
                                        <p>
                                            {{post.content | truncatechars:165}}
                                        </p>
                                        <a href="{% url 'blog:post' post.id %}" class="btn">Read more</a><!-- /.btn -->
                                    </div><!-- /.entry-content -->
                                </article><!-- /.post -->
                                {% endfor %}
                            </div><!-- /.list-posts -->
                            {% for post in posts %}
                              {{post.full_name|upper}}<br>
                            {% endfor %}
                            {% if posts.number > 6 %}
                            <nav class="pagination pagination-02">
                                <ul>
                                    {% if posts.has_previous %}
                                    <li><a href="?page={{posts.previous_page_number}}" aria-label="Previous">Previous</a></li>  
                                    {% endif %}
                                    {% for num in posts.paginator.page_range %}
                                      
                                        {% if posts.number == num %}
                                            <li class="active"><a href="#">{{num}}</a></li>
                                        {% elif num > posts.number|add:'-3' and num < posts.number|add:'3' %}
                                            <li><a href="?page={{ num }}">{{num}}</a></li>
                                        {% endif %}

                                    {% endfor %}
                                    {% if posts.has_next %}
                                        <li><a href="?page={{ posts.next_page_number }}" aria-label="Next">Next</a></li>                                          
                                    {% endif %}
                                </ul>
                            </nav><!-- /.pagination -->  
                            {% endif %}
                            
                        </div>
                        {% include "sidebar.html" %} 
                    </div><!-- /.row -->
                </div><!-- /.container -->
            </div><!-- /.padding -->
        </section><!-- /.main-content -->

{% endblock content %}

blog/templates/sidebar.html
<div class="col-sm-4">
    <aside class="sidebar text-center">
        <div class="widget widget_about_author">
            <h3 class="widget-title">About me</h3><!-- /.widget-title -->
            <div class="widget-details">
                <div class="author-avatar"><img src="/media/images/sidebar/mehrab.jpeg" alt="Avatar" class="img-circle"></div><!-- /.author-avatar -->
                <p>
                    I love so many things in the world,I'm a geek and a programmer. if I wnat to name my first degree, I must say Freedom
                </p>
                <div class="author-social">
                    <a href="#"><i class="fa fa-pinterest-p"></i></a>
                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-instagram"></i></a>
                </div><!-- /.author-social -->
            </div><!-- /.widget-details -->
        </div><!-- /.widget -->
        <div class="widget widget_newsletter">
            <h3 class="widget-title">Newsletter</h3><!-- /.widget-title -->
            <div class="widget-details">
                <form class="mc4wp-form" method="post">
                    <div class="mc4wp-form-fields"> 
                        <input class="form-control" type="email" name="EMAIL" placeholder="Email Address" required="">
                        <input type="submit" class="form-control" name="submit" value="Subscribe">
                    </div>
                    <div class="mc4wp-response"></div>
                </form>
            </div><!-- /.widget-details -->
        </div><!-- /.widget -->
        <div class="widget widget_recent_posts">
            <h3 class="widget-title">Recent Posts</h3><!-- /.widget-title -->
            <div class="widget-details">
                {% for post in recent_post %}
                <article class="post type-post media">
                        <div class="entry-thumbnail media-left pull-left"><img src="/media/{{post.picture}}" alt="Thumb Image"></div><!-- /.entry-thumbnail -->
                        <div class="entry-content media-body">
                            <h3 class="entry-title"><a href="{% url 'blog:post' post.id %}">{{post.title}}</a></h3><!-- /.entry-title -->
                            <span class="time"><time datetime="2017-12-05">{{post.publish_datetime}}</time></span><!-- /.time -->
                        </div><!-- /.entry-content -->
                </article><!-- /.post -->
                {% endfor %}
            </div><!-- /.widget-details -->
        </div><!-- /.widget -->
    </aside><!-- /.sidebar -->
</div>